url: https://shadowcatx.github.io

# Site settings
title: ATLab - Ideas for Auckland
email: test@domain.com
description: "Test description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/at
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty